language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: uMPJxFZToyVa+jqJU84XRdZGjx5w1Mgp/y/3JWghQSGEUH9zObMyKprBoK8N4LKkup61qseTP+LJEWB1qJBYCPFy7h9o1PdlaSvErJdjI9camYa9MFcRft8OLMy18imY3AUAw5F3eCGr9G8H0glp3GU0Ld+YvI6Q4TEyRZFTN2yA7kv6GH8GHUb//+H72v50OtWY+GxammEJEvuvEqrTq5iDliq/TO+NYaL//Myy1bLTtiOe98B/OSYDglb7t0mJLKZ3EW2/82VPG5+9X/UPvhT7BiWhI3exXk3wi6eDZrHd72jqAkALR+cbaOYaUNz8Wn5j3Gm4EGiVeECkUz3pdeZbrHRTHVQYWldZsp0bKtIww7kHxlRf1KcWX3ZZG3gG29lOey9iKDzuybdEuI6LozMGx8nOT3AuGA65cyU4s1qV+ISF84fopbgyY9Hzm9gXH/LVEPEJjv6M4wZlSCeT0aW/8ET11+cMMY7+5d1JF2dnEtpLzDcGkvrSc+XFHxyke3pxx0nqLH4sa3Nj/kzEoey/Zkin82H7ekmZE49X/RNgQ78NJEx5drMngnUR69vvoFkiutPrgrUCpzHtIBaQXwjawjr2/3VjThqhcs0UjUNBoFltBWKQsjKwzSlP/Tl1arzQ12Nimny1bjil28pOtotdK/IV5JZBG1RslGM62Pk=
  app: pacific-headland-50058 
  on:
    repo: YUZHENFEI/projet
