language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: Rnw9eSJ1fYQj+ZARH45jB0RvJBvyJAVN1wPhNZhIxFdSCKqTqgS9w5BEQnmtQxsscBmD1CvDAZaAqgwnkSU3Wc8I29sG/NjE57ep7HX0iS4mQCjWogWlBN+fUn/n2ET6SaRkbsOEGxBWM49fuRTOke7E4vw++ls62xRXeug0MIDUbccjjlCeOmPnxvuA9XPzrKEKjAptbQjgzAiVSalWPvcWxQ0ya7NjEzSQeCPEqQUdNxsjqbBg9vjIGtW28FtV5oou6KCBxumvGR0q1mIiri9+ujWmZ1l7/6vEbnPRrOd8qA+8XAS8ElrF5ZDQVuwZubEv9FVS9/y4Ros4n3nNp+kj7JaXy+Mkfvagin+JkrjSzUxUkl/ap7gdh66JNuHbkQN1p/dfgbyvHURA3vXpGdvSAb9yfajrjOpNH6gHgqy26h7tqedb3h+z2jqIBAHKseTPpGHgflwPQJfVr+U+K3IGh28uA3XkdzTYfBcQTYq8TBxB1KfPAs6EkgfVAGqHehVRqQoREpFZpeimQF38A2gQA3fvF9zk+9gcefZo/Vjm6EYdViDXRSkKJBqKqxsw4Dqlg6b8I6HdV1jkK7H5dKakLiz8RA9pxmylPIOAA+CllNb7H1tKczN9a/vAjljb0wBlEBIyxr7o5PW0TYysEZezo9RMs8PNAKkR/QFftEM=
  app: shrouded-refuge-36462
  on:
    repo: YUZHENFEI/projet
