language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: BMdnhIeREBfOeqYhZtiwePZXV99vnln2CfXvyDYfKo3mjpjECKk4cbchTd+OsjJKK0R1WeVzjxx+gKjzNoK8D9C8ge6rXmfBXssmNgi86w5fGxqNYMkLV0lir2s3OtJAquInwVYYJf1+VJDi8UJdpv+JSn6wOuvc1aI+3K/5IeVe6zZLjdSxZUsVq3+CYCu+7p95DLYu8Tvf9edm6IeBLMLcoZ5vqGQj70EvcXsrIgMdztpP5GWbwPhBC/9ONSp3CzbguMsYy0AaE/8fY2fNRs6Q/crxemKQ9UMPtv8Nfj2AzjcqPVERO2zjyBJ/NiQ3NFOu6MjKgNSIyyI8UnRIoN68w/S2RSWW2K2sKaxRA4zrByQ5rlLUY8zXmUq/x+2TMi61ENyzd7xFGa8QACeETRgGmsnyDHGBpQKwUN2YGBbHd48/XkLh3RJzUEjZwQPa1HOnYMI3nxZtIwbjQdcMP+a4bqmzum10kfKXyNw59C0IULxYsLPBL2t/kKcubhLrxe4uWYaEDn/Erj7EcLSg8PzykaytDERzAjr+j9ZPwq4AyaivVCNcEtl/Zo5RyfOkaM7YyjnKLDrqaZJa1OFImv7P9wyZk79LtT9vwIbAA1nKfKDV7ffMpPRfXs/nTyA/E/txa7bmdWXHLB1oKUZRQlU4Uglylr6iK4IsYOAQPF4=
  app: powerful-journey-80299
  on:
    repo: YUZHENFEI/projet
addons:
  code_climate:
    repo_token: c88fa675f620d2c0d4a38342a95fcd03042960cf1aa3e9c5c4963d01fd7889ea
after_success:
- bundle exec codeclimate-test-reporter
